---
- name: Setup ERP Next {{ erpnext_environment }}
  hosts: all
  become: true

  tasks:
    - ansible.builtin.import_tasks module: 
      file: tasks/essentials.yml

  roles:
    - role: docker
      tags:
        - docker

    # - role: containers/portainer
    #   tags:
    #     - portainer
    #     - containers
