---
- name: Setup ERP Next {{ erpnext_environment }}
  hosts: all
  become: true

  tasks:
    - name: Include essential tasks
      ansible.builtin.import_tasks:
        file: tasks/essentials.yml

  roles:
    - role: docker
      tags:
        - docker
    - role: containers/erpnext
      tags:
        - erpnext

    # - role: containers/portainer
    #   tags:
    #     - portainer
    #     - containers
