- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ docker_compose_dir}}/erpnext"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Copy the compose file
  template: 
    src: templates/erp.compose.yaml
    dest: "{{ docker_compose_dir }}/erpnext/compose.yaml"

- name: Start the compose stack
  community.docker.docker_compose:
    project_src: "{{ docker_compose_dir }}/erpnext"